name: otel-main

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Generate ref tag (latest)
        run: |
          echo "REF_TAG=latest" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/cmd/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: get otelcol-contrib
        run: make getotelcol

      - name: Build binnary (go build only)
        run: make binary
          
  package:
    if: ${{ github.event_name != 'pull_request' }} 
    needs: [ pre-build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate ref tag (latest)
        run: |
          echo "REF_TAG=latest" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/cmd/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/cmd/VERSION`" >> $GITHUB_ENV

      - name: Debug version
        run: echo ${{ env.VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      - name: Build otel infinity service
        shell: bash
        run: |
           make container

      - name: Push otel infinity container
        run: |
          docker push -a ghcr.io/leoparente/opentelemetry-infinity
