name: otel-update
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'
jobs:
  check:
    outputs:
      release: ${{ steps.early.outputs.release }}
    runs-on: ubuntu-latest
    steps:
      - id: early
        name: New version check
        run: |
          OTEL_LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/open-telemetry/opentelemetry-collector-releases/releases/latest)
          OTEL_LATEST_VERSION=$(echo $OTEL_LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
          INF_LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/leoparente/opentelemetry-infinity/releases/latest)
          INF_LATEST_VERSION=$(echo $INF_LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
          release=''
          if [[ $OTEL_LATEST_VERSION != $INF_LATEST_VERSION ]]; then
            release=$OTEL_LATEST_VERSION
          fi
          echo "release=$release" >> $GITHUB_OUTPUT
          
          
  release:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.release != ''
    steps:
      - uses: actions/checkout@v3
      - name: Version validation
        env:
          RELEASE: ${{needs.check.outputs.release}}
        run: |
          echo "releaseee $RELEASE"
